# Generated by Django 3.2.12 on 2024-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
