# Generated by Django 3.2.12 on 2024-11-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
