# Generated by Django 5.1.5 on 2025-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
