# Generated by Django 5.1.5 on 2025-01-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_is_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_changed',
            new_name='is_edited',
        ),
    ]
