# Generated by Django 5.1.5 on 2025-01-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rename_is_edited_message_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='edited',
            new_name='is_changed',
        ),
    ]
