# Generated by Django 5.1.6 on 2025-02-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_message_is_read_delete_messagereadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
