# Generated by Django 5.1.7 on 2025-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_chat_avatars/'),
        ),
    ]
